#!/usr/bin/env python3
"""Review a PR diff with the OpenAI Responses API and print Markdown to stdout.

Dependency-free (stdlib only). Reads the diff from the path in DIFF_FILE,
calls the model named in OPENAI_MODEL, and writes the review to stdout so the
workflow can post it as a single PR comment.
"""
import json
import os
import sys
import urllib.error
import urllib.request

API_URL = "https://api.openai.com/v1/responses"
# Keep well under the model context window; very large diffs get truncated.
MAX_DIFF_CHARS = 120_000

SYSTEM_PROMPT = """You are a senior engineer reviewing a multi-tenant app's PR diff.
Be concise and specific; reference file names. Skip style nitpicks.

Tenant isolation is enforced by a Mongoose plugin (`src/models/plugins/tenantScope.ts`).
It cannot enforce isolation on things outside it — flag DB changes that escape the
plugin: a tenant-data model missing `.plugin(tenantScope)`, raw driver access
(`Model.collection.*`, `connection.db`), `bulkWrite`/`estimatedDocumentCount`,
`aggregate` with `$lookup`/`$merge`/`$out`, or `runWithoutTenant` bypasses.

Then review correctness bugs, other security issues, and clear design problems.

Reply in Markdown, omitting empty sections:
## 🏢 Tenant isolation
## 🐛 Bugs & correctness
## 🔒 Other security
## 🧹 Suggestions
One line per bullet, naming the file."""


def read_diff() -> str:
    path = os.environ.get("DIFF_FILE", "")
    if not path or not os.path.exists(path):
        sys.exit("DIFF_FILE not set or missing")
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        diff = fh.read()
    if not diff.strip():
        return ""
    if len(diff) > MAX_DIFF_CHARS:
        diff = diff[:MAX_DIFF_CHARS] + "\n\n[diff truncated — too large to review in full]"
    return diff


def call_openai(diff: str) -> str:
    api_key = os.environ["OPENAI_API_KEY"]
    model = os.environ.get("OPENAI_MODEL", "gpt-5.5")
    max_tokens = int(os.environ.get("OPENAI_MAX_OUTPUT_TOKENS", "4000"))

    body = {
        "model": model,
        "instructions": SYSTEM_PROMPT,
        "input": f"Review this pull request diff:\n\n```diff\n{diff}\n```",
        "max_output_tokens": max_tokens,
    }
    req = urllib.request.Request(
        API_URL,
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as err:
        detail = err.read().decode("utf-8", errors="replace")
        sys.exit(f"OpenAI API error {err.code}: {detail}")
    except urllib.error.URLError as err:
        sys.exit(f"OpenAI request failed: {err}")

    return extract_text(payload)


def extract_text(payload: dict) -> str:
    """Pull the assistant text out of a Responses API payload."""
    # Convenience field present in some responses.
    if payload.get("output_text"):
        return payload["output_text"].strip()
    parts = []
    for item in payload.get("output", []):
        if item.get("type") != "message":
            continue
        for chunk in item.get("content", []):
            if chunk.get("type") == "output_text" and chunk.get("text"):
                parts.append(chunk["text"])
    text = "\n".join(parts).strip()
    if not text:
        sys.exit(f"Could not parse model output: {json.dumps(payload)[:2000]}")
    return text
# The main function orchestrates reading the diff, calling the API, and printing the review.

def main() -> None:
    diff = read_diff()
    if not diff:
        print("_No code changes to review._")
        return
    review = call_openai(diff)
    print("## 🤖 ChatGPT Code Review\n")
    print(review)
    print(f"\n\n<sub>Generated by `{os.environ.get('OPENAI_MODEL', 'gpt-5.5')}` "
          "via the Responses API.</sub>")


if __name__ == "__main__":
    main()
