services:
  app:
    build: .
    container_name: grocery_store_chatbot
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    container_name: grocery-shop_redis_cache
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: